baseURL = 'https://www.macdonaldeditorial.com/'
languageCode = 'en-us'
title = 'MacDonald Editorial'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "MacDonald Editorial"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Brian MacDonald"
  favicon = ""
  site_logo = ""
  description = "MacDonald Editorial"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 5
  body_classes = "georgia bg-near-white"
  mainSections = ['posts']

[[params.ananke_socials]]
name = "mastodon"
url = "https://jawns.club/@bmac"